name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 添加写入权限
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
        
    - name: Run tests
      run: |
        pytest scripts/test_*.py -v
        
    - name: Validate data files
      run: |
        for file in data/*.md data/*/*.md; do
          if [ -f "$file" ]; then
            echo "Validating $file..."
            python scripts/validate.py "$file"
          fi
        done
        
    - name: Update stats and badges
      run: |
        python scripts/stats.py
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md stats/badges.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "自动更新：数据统计和徽章" && git push) 